In [4]:
# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

#1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
import numpy as np

arr1= np.random.randint(1, 20, (5, 5))
arr1[:, 2] = 1
arr1

#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

arr2 = np.arange(1, 17).reshape(4, 4)
np.fill_diagonal(arr2, 0)

In [49]:


### Assignment 2: Array Indexing and Slicing

# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
arr4=np.arange(1, 37).reshape(6, 6)
sub_arr4 = arr4[2:5, 1:4]
# 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
arr5 = np.random.randint(1, 100, (5, 5))
print(arr5)
arr6=arr5[1,:]
arr6=np.concatenate(arr5[1:5,1],arr5[1:4,1],arr5[4,:],arr5[0,:])
print(arr6)
print(arr5[1:4,1])
print(arr5[4,:])
print(arr5[0,:])




[[27 86 51 61 17]
 [50 75 11 54 30]
 [55 27 50 73 22]
 [16 49 98 49 71]
 [66 52 29 72 33]]


TypeError: concatenate() takes from 1 to 3 positional arguments but 4 were given

In [ ]:

# ### Assignment 3: Array Operations

# 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.


In [ ]:

# ### Assignment 4: Statistical Operations

# #1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
# #2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [ ]:

# ### Assignment 5: Broadcasting

# #1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

import numpy as np
array33= np.random.randint(1,20, size = (3,3))
array33

arr_shape3 = np.random.randint(1,5, size = (3,))
result = array33+arr_shape3
result


array([[12, 19,  7],
       [12,  3, 17],
       [ 6,  8, 15]], dtype=int32)

In [24]:

# #2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.
array44 = np.random.randint(1,56, size = (4,4))
array_oneD = np.random.randint(1,4, size = (4,))

result = array44-array_oneD[:,np.newaxis]
result

array([[18, 53,  6, 40],
       [47, 29, 47, 44],
       [38, 51, 20, 37],
       [30, 20, 10, 21]], dtype=int32)

In [ ]:

# ### Assignment 6: Linear Algebra

# #1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
# #2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.
import numpy as np

arr2 = np.random.randint(1,10, size= (3,3))
print (arr2)

matrix = np.array(arr2)  ## making a mtrix out of the array
determinant = np.linalg.det(matrix)
inverse = np.linalg.inv(matrix)
eigenValues = np.linalg.eig(matrix)
# print("Determinant: ", determinant)
# print("inverse: ", inverse)
# print("eigenValue: ", eigenValues)

array23 = np.arange(1,7).reshape(2,3)
array32 = np.arange(8,14).reshape(3,2)

array32 
array23
# Ensure that the dimensions of the matrices are 
# compatible for multiplication. For example, if A is of shape (m, n),
#  then B must be of shape (n, p).
# The resulting matrix will have the shape (m, p).
array_multiply = np.dot(array23,array32)
array_multiply


In [26]:

# ### Assignment 7: Advanced Array Manipulation

# 1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

arr337 = np.arange(1,10).reshape(3,3).reshape(1,9).reshape(9,1)
arr337

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [30]:

# 2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).
array552 = np.random.randint(1,21,size=(5,5))

flat_array= array552.flatten()
flat_array

array([ 9,  3,  1, 10,  7, 20, 11,  5, 17, 11,  3, 19,  2,  1, 18,  2, 13,
        9, 19,  8, 11, 10,  3, 13, 20], dtype=int32)

In [31]:

# ### Assignment 8: Fancy Indexing and Boolean Indexing

# 1. Create a NumPy array of shape (5, 5) filled with random integers.
# What is Fancy Indexing in NumPy?
# Fancy indexing is a powerful feature in NumPy that allows you to access and manipulate
# elements of an array using arrays of indices rather than simple integer indices.
# This enables you to extract or modify multiple elements at once in a more flexible way.

# How It Works in Your Example
# In your code, you created a 5x5 NumPy array filled with random integers and 
# then used fancy indexing to extract the corner elements. Here’s a breakdown of how it works:
#  Use fancy indexing to extract the elements at the corners of the array.
array55 = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array55)
corners= array55[[0,0,-1,-1],[0,-1,0,-1]]
print(corners)

Original array:
[[14 17 19  7 20]
 [ 7 10  8 15 10]
 [13  7  7  6  5]
 [ 6  9  4  8 11]
 [ 8 16 17 16 15]]
[14 20  8 15]


In [33]:


# 2. Create a NumPy array of shape (4, 4) filled with random integers.
#  Use boolean indexing to set all elements greater than 10 to 10.
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)
array[array>10]=10
print("Modified array: ", array)




Original array:
[[ 2 16 12 17]
 [ 9 13  8  4]
 [ 6 19  8  1]
 [17 19 18  1]]
Modified array:  [[ 2 10 10 10]
 [ 9 10  8  4]
 [ 6 10  8  1]
 [10 10 10  1]]


In [35]:

# ### Assignment 9: Structured Arrays

# 1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
data_type2 = [('name','U10'), ('age','i4'), ('weight','f4')]
data = np.array([('Alice',25,55.5),('Bob',30,85.3),('Charlie',20,65.2)], dtype= data_type2)

print(data)
sorted_array = np.sort(data, order= 'age')
sorted_array

[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]


array([('Charlie', 20, 65.2), ('Alice', 25, 55.5), ('Bob', 30, 85.3)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [38]:

# 2. Create a structured array with fields 'x' and 'y' (both integers).
#  Add some data and compute the Euclidean distance between each pair of points.
data_type3=[('x','i4'),('y','i4')]
data2= np.array([(1,2),(3,4),(4,5)],dtype=data_type3)
distances =np.sqrt((data2['x'][:,np.newaxis]-data2['x'])**2 +(data2['y'][:,np.newaxis]- data2['y'])**2)

distances

array([[0.        , 2.82842712, 4.24264069],
       [2.82842712, 0.        , 1.41421356],
       [4.24264069, 1.41421356, 0.        ]])

In [39]:
# ### Assignment 10: Masked Arrays
# What is a Masked Array?
# A masked array is a special type of array in
# NumPy that allows you to handle missing or
# invalid entries in your data. It consists of two main components:

# Data Array: The actual data values.
# Mask: A boolean array that indicates which elements are valid (unmasked)
# and which are invalid (masked). Masked elements are typically
# represented as -- when printed.
# Why Use Masked Arrays?
# Masked arrays are useful in scenarios where you want to perform
# calculations while ignoring certain values. For example, if you have 
# an array of measurements and some values are outliers or invalid, you 
# can mask those values and compute statistics (like sums or means) only on the valid data.

# 1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
import numpy.ma as ma
original_array = np.random.randint(1,16, size = (4,4))

masked_array = ma.masked_greater(original_array,10)
print("Original Array")
print(original_array)
print("Masked Array ")
print(masked_array)

Original Array
[[ 4  9 10  7]
 [ 2 11 13  5]
 [11  6  2  8]
 [ 3 13  2  3]]
Masked Array 
[[4 9 10 7]
 [2 -- -- 5]
 [-- 6 2 8]
 [3 -- 2 3]]


In [ ]:

# 2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. 
# ma.masked_array(): This function creates a masked array from the given data (original_array2). The mask parameter specifies which elements to mask.
# np.eye(3, dtype=bool): This creates a 3x3 identity matrix where the diagonal elements are True 
# and all other elements are False. When passed as the mask, it indicates that the diagonal elements 
# of original_array2 should be masked.
# Replace the masked elements with the mean of the unmasked elements.

original_array2 = np.random.randint(1,7,size=(3,3))
masked_array2= ma.masked_array(original_array2, mask= np.eye(3,dtype=bool))
print("Original Array ")
print(original_array2)
print("Masked array : ")
print(masked_array2)

# masked_array2.filled(mean_unmasked): This function returns a new array
# where all masked elements are replaced with the specified 
# value (mean_unmasked). This allows you to fill in the masked positions with the calculated mean.
mean_unmasked= masked_array2.mean()
masked_array2 = masked_array2.filled(mean_unmasked)

print(masked_array)


# np.random.randint(): Generates an array of random integers.
# ma.masked_array(): Creates a masked array, allowing you to specify which elements to mask.
# np.eye(): Generates an identity matrix, useful for creating masks.
# mean(): Computes the mean of the unmasked elements in the masked array.
# filled(): Replaces masked elements with a specified value.






Original Array 
[[5 5 3]
 [4 6 6]
 [4 5 1]]
Masked array : 
[[-- 5 3]
 [4 -- 6]
 [4 5 --]]
[[4 9 10 7]
 [2 -- -- 5]
 [-- 6 2 8]
 [3 -- 2 3]]
